### ISSUE TITLE
Problem with dicom conversion

### ISSUE THREAD

**Issue by zhenghanQ** [gablab/analysis#2]
I was batch converting a number of subjects' dicoms to nifti and found the conversion failed only on one of them, which I have never seen before.
/mindhive/xnat/dicom_storage/CASL/CASL13109

The nifti files are saved at
/mindhive/xnat/data/CASL/CASL13109
You'll see there is only one nifti file generated there...

scripts I used: 
/gablab/p/CASL/Analysis/convert_recon/bips/dicom_conversion.json
/gablab/p/CASL/Analysis/convert_recon/scripts/convert-dicoms-pipeline.py

I didn't see any error messages. Here is the working directories for the scripts above.
/mindhive/scratch/Sun/zqi/convert_workflow/_subject_id_CASL13109
/mindhive/scratch/Sun/zqi/dicom_conversion_pipeline/_subject_id_CASL13109

**Comment by tylerper** [comment]
Sometimes the scanner fails to write the "session" number at the prefix of the dicom files.
The dicom-convert script you're using expects dicoms files of the following format:
xxxxxx-yy-zzz.dcm
where the x are the session number (which is taken from the "study time" field of the dicom header (in fractional seconds)), the y are the dicom series number for that session, and the z are the volume (or slice) number for that series.

For example, the dicom file: 
921000-1-1.dcm
is the first volume of the first scan series (e.g., the saggital plane of the localizer). The prefix comes from the study time.  We can show this using the program "dicom_hdr" provided with AFNI:

``` bash
$ dicom_hdr 921000-1-1.dcm | grep "Study Time"
0008 0030       14 [256     ] //                  ID Study Time//111036.921000
```

However, if the study time field has no fractional seconds (e.g., 

``` bash
0008 0030       14 [256     ] //                  ID Study Time//085418.000000
```

Then the scanner will only write:
yy-zzz.dcm

This can be easily fixed by renaming all the dicom files to have an arbitrary prefix:

``` bash
$ cd /path/to/subject/dicoms
$ for i in *.dcm; do mv -v ${i} 555555-${i}; done
```

**Comment by zhenghanQ** [comment]
Great! Thanks a lot, Tyler! :+1:
